
name: publish-book

on:
  # Trigger the workflow on push to main branch
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml@main
    with:
      environment_name: leap-docs-env
      path_to_notebooks: 'book'

  deploy:
    needs: build
    uses: jbusecke/cookbook-actions/.github/workflows/deploy-book.yaml@patch-3 #hack until https://github.com/ProjectPythia/cookbook-actions/pull/45 is merged. 
    with:
      publish_dir: "book/_build/html"
